name: Librus to Obsidian Sync

on:
  schedule:
    # Codziennie o 6:00 czasu UTC (czyli 7:00 lub 8:00 w PL)
    - cron: '0 6 * * *'
  # Pozwala na ręczne uruchomienie skryptu z poziomu WWW
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Pobieranie repozytorium scrapera
      uses: actions/checkout@v4

    - name: Konfiguracja Pythona
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalacja bibliotek
      run: pip install -r requirements.txt

    - name: Uruchomienie Bota
      env:
        LIBRUS_LOGIN: ${{ secrets.LIBRUS_LOGIN }}
        LIBRUS_PASS: ${{ secrets.LIBRUS_PASS }}
        SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
        SMTP_PORT: ${{ secrets.SMTP_PORT }}
        SMTP_USER: ${{ secrets.SMTP_USER }}
        SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python main.py

    - name: Zapisz zrzut ekranu w razie bledu
      if: failure() # Ten krok uruchomi sie TYLKO, gdy bot wyrzuci błąd
      uses: actions/upload-artifact@v4
      with:
        name: error-screenshot
        path: error_headless.png
        if-no-files-found: ignore

    - name: Commit i push zmian do repozytorium
      run: |
        git config --global user.email "bot@librus.com"
        git config --global user.name "Librus Scraper Bot"
        
        git add history.json Librus_Pelny_Terminarz.md
        
        if git diff-index --quiet HEAD; then
          echo "Brak zmian w kalendarzu, nic nie wysyłam."
        else
          git commit -m "Aktualizacja terminarza z Librusa: $(date +'%Y-%m-%d') [skip ci]"
          git push
        fi
